version: '3'
services:
# use "start-dev" for testing and "start" for production. Change 8443 to 8080 and https to http
# Remember to change the rabbitmq.conf file as well to http://ipaddr:8080 when using "start-dev"
  oidc_kc:
    container_name: oidc
    image: quay.io/keycloak/keycloak:20.0
    entrypoint: /opt/modify_postgres.sh
    command: >
      -v start
      --import-realm
    volumes:
      - ./certs/:/opt/keycloak/conf/
      - ./oidc/import/:/opt/keycloak/data/import/
      - ./oidc/providers/:/opt/keycloak/providers/
      - ./oidc/themes/:/opt/keycloak/themes/
      - ./postgres/modify_postgres.sh:/opt/modify_postgres.sh
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_ADMIN_URL: https://${LOCAL_IP}:8443
      KC_HOSTNAME_URL: https://${LOCAL_IP}:8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/oidc.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/oidc.key
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB: postgres
      KC_DB_URL_HOST: ${LOCAL_IP}
    network_mode: host  
      
  postgres_db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres/setup_postgres.sh:/tmp/setup_postgres.sh
      - ./postgres/modify_postgres.sh:/opt/modify_postgres.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    networks:
      - net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - net
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12
    volumes:
      - ./rabbitmq/signing-key.pem:/etc/rabbitmq/signing-key.pem
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./certs/root_ca.crt:/etc/rabbitmq/root_ca.crt:ro
      - ./certs/rabbitmq.crt:/etc/rabbitmq/rabbitmq.crt:ro
      - ./certs/rabbitmq.key:/etc/rabbitmq/rabbitmq.key:ro
    network_mode: host  
      
  ldap_mock:
    container_name: ldap
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - "3890:389"
    networks:
      - net
      
  ldapgui:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldapgui
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap://${LOCAL_IP}:3890
    networks:
      - net
      
networks:
  net:
