version: '3'
services:
# use "start-dev" for testing and "start" for production. Change 8443 to 8080 and https to http
# Remember to change the rabbitmq.conf file as well to http://ipaddr:8080 when using "start-dev"
  oidc_kc:
    container_name: oidc
    image: quay.io/keycloak/keycloak:20.0
    entrypoint: /opt/modify_postgres.sh
    command: >
      -v start
      --import-realm
    volumes:
      - ./certs/:/opt/keycloak/conf/
      - ./oidc/import/:/opt/keycloak/data/import/
      - ./oidc/providers/:/opt/keycloak/providers/
      - ./oidc/themes/:/opt/keycloak/themes/
      - ./postgres/modify_postgres.sh:/opt/modify_postgres.sh
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_ADMIN_URL: https://${LOCAL_IP}:8443
      KC_HOSTNAME_URL: https://${LOCAL_IP}:8443
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/oidc.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/oidc.key
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB: postgres
      KC_DB_URL_HOST: ${LOCAL_IP}
    network_mode: host  
      
  postgres_db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./postgres/setup_postgres.sh:/tmp/setup_postgres.sh
      - ./postgres/modify_postgres.sh:/opt/modify_postgres.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    networks:
      - net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@postgres.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - net
      
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12
    volumes:
      - ./rabbitmq/signing-key.pem:/etc/rabbitmq/signing-key.pem
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./certs/root_ca.crt:/etc/rabbitmq/root_ca.crt:ro
      - ./certs/rabbitmq.crt:/etc/rabbitmq/rabbitmq.crt:ro
      - ./certs/rabbitmq.key:/etc/rabbitmq/rabbitmq.key:ro
    network_mode: host  
      
  ldap_mock:
    container_name: ldap
    image: osixia/openldap
    environment:
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_CRT_FILENAME: ldap.crt
      LDAP_TLS_CA_CRT_FILENAME: root_ca.crt
    volumes:
      - ./certs/phpldap.key:/container/service/slapd/assets/certs/ldap.key:rw
      - ./certs/phpldap.crt:/container/service/slapd/assets/certs/ldap.crt:rw
      - ./certs/root_ca.crt:/container/service/slapd/assets/certs/root_ca.crt:rw
      - ./ldap_mock/mock_users.ldif:/tmp/mock_users.ldif
      - ./ldap_mock/mock_users_update.ldif:/tmp/mock_users_update.ldif
    ports:
      - "3890:389"
    networks:
      - net
      
  ldapgui:
    image: osixia/phpldapadmin:0.9.0
    container_name: ldapgui
    command: >
      -ldapmodify -h localhost -D "cn=admin,dc=example,dc=org" -w admin -a -f /tmp/mock_users.ldif
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap://${LOCAL_IP}:3890
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: phpldap.key
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: phpldap.crt
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: root_ca.crt
    volumes:
      - ./certs/phpldap.key:/container/service/phpldapadmin/assets/apache2/certs/phpldap.key:rw
      - ./certs/phpldap.crt:/container/service/phpldapadmin/assets/apache2/certs/phpldap.crt:rw
      - ./certs/root_ca.crt:/container/service/phpldapadmin/assets/apache2/certs/root_ca.crt:rw
    networks:
      - net
      
networks:
  net:
    